#!/bin/bash
#
# install adb and enable development in your phone

#adb shell pm list packages -f | grep data | awk -F":" '{print $2}' | awk -F"=" '{print "adb pull "$1}'  > get_all_extra_packages
adb shell pm list packages -f | grep data | awk -F":" '{print $2}' | awk -F"=" '{print "adb pull "$1}'  > part1
adb shell pm list packages -f | grep data | awk -F"-" '{print $1".apk"}' | awk -F"\/" '{print $4}' > part2
paste part1 part2 > get_all_extra_packages
sh get_all_extra_packages
